name: anygrasp39
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.11.12
  - cudatoolkit-dev=11.3.1
  - expat=2.7.3
  - ld_impl_linux-64=2.44
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - libnsl=2.0.0
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.6.0
  - pip=25.3
  - pthread-stubs=0.3
  - python=3.9.25
  - python_abi=3.9
  - readline=8.3
  - setuptools=80.9.0
  - sqlite=3.51.0
  - tk=8.6.15
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - addict==2.4.0
      - asttokens==3.0.1
      - attrs==25.4.0
      - autolab-core==1.1.1
      - autolab-perception==1.0.0
      - blinker==1.9.0
      - catkin-pkg==1.1.0
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - click==8.1.8
      - colorlog==6.10.1
      - comm==0.2.3
      - configargparse==1.7.1
      - contourpy==1.2.1
      - cvxopt==1.3.2
      - cycler==0.12.1
      - cython==0.29.37
      - dash==3.3.0
      - decorator==5.2.1
      - dexnet==0.2.0
      - dill==0.4.0
      - docutils==0.22.3
      - empy==3.3.4
      - exceptiongroup==1.3.0
      - executing==2.2.1
      - fastjsonschema==2.21.2
      - ffmpeg-python==0.2.0
      - flask==3.1.2
      - fonttools==4.60.1
      - future==1.0.0
      - grasp-nms==1.0.2
      - graspclutter6dapi==0.0.2
      - graspnetapi==1.2.11
      - h5py==3.14.0
      - idna==3.11
      - imageio==2.33.1
      - importlib-metadata==8.7.0
      - importlib-resources==6.5.2
      - ipython==8.18.1
      - ipywidgets==8.1.8
      - itsdangerous==2.2.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - joblib==1.5.2
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter-core==5.8.1
      - jupyterlab-widgets==3.0.16
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - markupsafe==3.0.3
      - matplotlib==3.7.5
      - matplotlib-inline==0.2.1
      - minkowskiengine==0.5.4
      - multiprocess==0.70.18
      - narwhals==2.11.0
      - nbformat==5.7.0
      - nest-asyncio==1.6.0
      - networkx==2.8.8
      - ninja==1.11.1
      - numpy==1.23.4
      - open3d==0.18.0
      - opencv-python==4.5.5.64
      - packaging==25.0
      - pandas==2.0.3
      - parso==0.8.5
      - pexpect==4.9.0
      - pillow==9.4.0
      - platformdirs==4.4.0
      - plotly==6.4.0
      - pointnet2==0.0.0
      - prompt-toolkit==3.0.52
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pygments==2.19.2
      - pyparsing==3.2.5
      - pyquaternion==0.9.9
      - pyserial==3.5
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pywavefront==1.3.3
      - pywavelets==1.4.1
      - pyyaml==6.0.3
      - referencing==0.36.2
      - requests==2.32.5
      - retrying==1.4.2
      - rpds-py==0.27.1
      - ruamel-yaml==0.18.16
      - ruamel-yaml-clib==0.2.14
      - scikit-image==0.19.3
      - scikit-learn==1.6.1
      - scipy==1.10.1
      - setproctitle==1.3.7
      - six==1.17.0
      - stack-data==0.6.3
      - threadpoolctl==3.6.0
      - tifffile==2022.8.12
      - torch==1.9.0+cu111
      - torchvision==0.10.0+cu111
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transforms3d==0.3.1
      - trimesh==4.11.0
      - typing-extensions==4.15.0
      - tzdata==2025.2
      - urllib3==2.5.0
      - wcwidth==0.2.14
      - werkzeug==3.1.3
      - widgetsnbextension==4.0.15
      - zipp==3.23.0

